dataset_path: "dataset/accident"
model_path: "model/anomaly_detector.joblib"

audio:
  sample_rate: 48000
  duration: 1
  channels: 1
  yamnet_sample_rate: 16000
  buffer_size: 20

model:
  contamination: "auto"
  n_estimators: 100
  threshold_percentile: 5
  grid_search: false
  update_interval: 0.5